version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: bibliotech-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bibliotech
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
